### ISSUE TITLE
smtp_client.dart - Future already completed

### ISSUE THREAD

**Issue by GXLabonte** [kaisellgren/mailer#19]
onSend.listen((Envelope mail) {
          if (mail == envelope) {
            timeout.cancel();
  97       completer.complete(true);
          }
        }, onError: (e) {
          _close();
          timeout.cancel();
102    completer.completeError('Failed to send an email: $e');
        });

        return completer.future;

The completer at line 97 is executed, and then the completer on line 102 in executed. Resulting in an error:
Unhandled exception:
Uncaught Error: Bad state: Future already completed

**Comment by stwupton** [comment]
This is becoming a real issue for me. Are there any plans to have this fixed?

**Comment by kaisellgren** [comment]
I'll look at this today.

**Comment by kaisellgren** [comment]
How did you get this? Did you try to send the same Envelope instance twice?

**Comment by stwupton** [comment]
I am sending it just the once. But I do get this error every single time. Here's the code that I'm executing:

```java
void _sendConfirmationEmail(String id, String email){

	SmtpOptions options = new SmtpOptions()
		..hostName = "<hostname>"
		..port = 25
		..username = "noreply@indecks.co"
		..password = "<password>"
		..requiresAuthentication = true;

	SmtpTransport emailTransport = new SmtpTransport(options); 

	Envelope envelope = new Envelope()
		..from = "noreply@indecks.co"
		..fromName = "Indecks"
		..recipients = [email]
		..subject = "Confirm Email | Indecks"
		..html = """<Content>""";

	emailTransport.send(envelope);

}
```

Thanks for looking into this.

**Comment by kaisellgren** [comment]
Can you verify one thing -- did the email arrive and you saw this exception, or did it not arrive at all?

**Comment by kaisellgren** [comment]
It would also be really helpful, if you could modify your local mailer.dart file and add this function at the bottom of the file:

```dart
printDebugInformation() {
  _logger.onRecord.listen(print);
}
```

and then before sending the email, you would just call the function: `printDebugInformation()` and then try it again and paste your debug info here.

**Comment by kaisellgren** [comment]
Another question, is it possible the email submission is taking over 60 seconds?

**Comment by kaisellgren** [comment]
Final question, are you sending a single email or multiple? Thanks for the information!

**Comment by stwupton** [comment]
Yeah the email does arrive. 

I will do that now.

No it only takes a few seconds, then the exception is thrown.

No I am sending just the one.

**Comment by kaisellgren** [comment]
I updated the package with improvements. Can you try the latest version as well?

**Comment by stwupton** [comment]
@kaisellgren I pasted and executed that debug function you provided me with yesterday and nothing was being printed. I have just tested it with the changes that you made on the package and it is still not printing anything and unfortunately, the error still persists.

**Comment by kaisellgren** [comment]
Can you try another email provider like gmail to see if its a service
related issue?

**Comment by stwupton** [comment]
@kaisellgren Thank you for pointing that out as it worked perfectly fine using `GmailSmtpOptions`. I will have to look into this. Do you know how I can catch the error in the meantime, just so that the server doesn't stop every time an email is sent? Thanks again.

**Comment by kaisellgren** [comment]
Can you let me know how you fixed it? What was the issue? If it required changes to mailer you can submit me a patch or fork and send a pull request? Or perhaps you just did something silly?

Errors should propagate through the Future chain, so if you do `.catchError()` on the send result it should not crash your app.

**Comment by stwupton** [comment]
It would probably be classed as silly. I didn't realize that I was sending the emails through the **Non-SSL** settings. But I changed the hostName and port so that it was being sent securely with SSL/TLS. 

Ah, of course. I'm quite new to Dart and this catching and throwing concept. I was trying to resolve it with `try {} catch(e) {}`.

**Comment by kaisellgren** [comment]
The try-catch block won't work. You need to `catchError()`. When you write programs, you generally chain your futures with `then()` or via other means. Look for the official article about Futures.

**Comment by kbirch** [comment]
This is happening to me as well.  The email sends fine (and quickly) but I'm always getting this "Future already completed" error.  I couldn't get printDebugInformation working either, so I just added a print statement at the spot the issue is occurring (sample below starts at line 100 of smtp_client.dart):

```
        onSend.listen((Envelope mail) {
          if (mail == envelope) {
            timeout.cancel();
            completer.complete(mail);
          }
        }, onError: (e) {
          _close();
          timeout.cancel();
          print('Failed to send an email: $e');
          completer.completeError('Failed to send an email: $e');
        }, cancelOnError: true);
        return completer.future;
      });
```

My code is this:

```
    var transport = new SmtpTransport(_options);

    var envelope = new Envelope()
      ..from = fromAddress
      ..fromName = fromName
      ..recipients = recipients
      ..subject = subject
      ..text = text
      ..html = html;

    transport.send(envelope).catchError((e) {
      // Logging code
    });
```

Here's what is output...

```
Failed to send an email: TlsException: OSStatus = -9805: connection closed gracefully error -9805
API server has unexpectedly stopped: Bad state: Future already completed #0      _Completer.completeError (dart:async/future_impl.dart:21)
#1      SmtpClient.send.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:mailer/src/smtp/smtp_client.dart:109:21)
#2      _rootRunUnary (dart:async/zone.dart:1158)
#3      _CustomZone.runUnary (dart:async/zone.dart:1037)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:352)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:365)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:267)
<snip>
```

As I mentioned, the email arrives at its destination just fine. Appreciate any help or insight you can offer.
